name: HTML Validation Pipeline

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Validate the index.html file existence
      - name: Validate HTML File
        run: |
          if [ ! -f index.html ]; then
            echo "Error: index.html file is missing!"
            exit 1
          else
            echo "index.html file exists."
          fi
